### ISSUE TITLE
Can't sync between spotify and deezer

### ISSUE THREAD

**Issue by AleD219** [XDGFX/ultrasonics#19]
Hi. I have a problem with syncing spotify and deezer playlists. 

here's a log of the crash:
https://hasteb.in/awajodem.lua

**Comment by jhthenerd** [comment]
I believe the `songs` parameter has been changed to tracks. [This is likely the line that needs to be updated.
](https://github.com/XDGFX/ultrasonics/blob/767a68bd550d57250025d88faaab105804ccd5b3/ultrasonics/official_plugins/up_deezer.py#L519)
See: https://developers.deezer.com/api/playlist#infos

**Comment by XDGFX** [comment]
Sorry for the massive delay!

It should be working as it is, when updating a playlist `"songs"` is the correct key to use. The url is `"https://api.deezer.com/playlist/{playlist_id}/tracks"`
https://developers.deezer.com/api/actions-post

![image](https://user-images.githubusercontent.com/16356208/129278919-ab1e165a-4f66-4147-8870-2444bea72896.png)

I've just pushed a couple of changes to the Deezer plugin, maybe try pulling them and let me know if you're still having problems?

**Comment by froman753** [comment]
When will the DockerHub be updated? Or is there a way to manually sync the Gtihub changes with the docker version?

**Comment by AleD219** [comment]
clone the repo, cd in the cloned repo and write:
`docker build -t imagename:revision .`

and you will build a docker image with the latest changes.

**Comment by floookay** [comment]
Hi, I pulled the latest changes and didn't experience any issues with transferring playlists from deezer to spotify or vice versa.  
Ty, glad I found this today :)

**Comment by XDGFX** [comment]
Nice! Glad to have feedback from some of the services I don't use personally. I'll close this issue for now as there doesn't seem to be an issue with Deezer.
