### ISSUE TITLE
Stuck on starting webserver

### ISSUE THREAD

**Issue by sanskarlather** [XDGFX/ultrasonics#26]
I have tried setting ultrasonics up using both docker and python on windows both time I get stuck on starting webserver for hours I don't know what is the cause of this issue. I am attaching the entire logs folder so this issue can be resolved.
[logs.zip](https://github.com/XDGFX/ultrasonics/files/7014170/logs.zip)

**Comment by XDGFX** [comment]
I don't see any errors in your logs. How are you trying to access ultrasonics? If it's on the same machine you should be able to open localhost:5000 in manual mode. If using Docker make sure to forward port 5000 from inside the container.

```bash
docker run -p 5000:5000 xdgfx/ultrasonics
```

Then go to localhost:5000 in your browser. Maybe you have some firewall setup which is limiting your access? Could be worth *temporarily* disabling Windows Firewall to see if it's interferring.

**Comment by XDGFX** [comment]
Closing as I haven't heard back, feel free to re-open if you are still stuck!
